name: Pull Request Comment Trigger Example
on:
  issue_comment:
    types: [created]

jobs:
  rebase:
    runs-on: ubuntu-latest
    # if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: please merge
        env:
          GH_TOKEN: ${{ github.token }}
        if: contains(github.event.comment.body, '/rebase')
        run: 'gh pr create --title "merge-main-into-staging" --body "merge-main-into-staging" --base staging'
